### ISSUE TITLE
 python preprocess_rgc.py

### ISSUE THREAD

**Issue by kjhhhh** [Control-xl/Medical-Vision-Langauge-Transformer#4]
Traceback (most recent call last):
  File "preprocess_rgc.py", line 55, in <module>
    preprocess_pretrain()
  File "preprocess_rgc.py", line 17, in preprocess_pretrain
    RGC_data = json.load(open(ann_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/RGC/RGC_annotation.json'
How can I get this file?

**Comment by dhr613** [comment]
I have the same question,may it was deleted or missed.Did you solve this question?

**Comment by taqihaider7** [comment]
I also have the same question. @Control-xl, could you upload the file ?
